---
driver:
  name: vagrant

provisioner:
  name: ansible
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: true
  ansible_verbosity: 2
  ansible_verbose: true

platforms:
  - name: centos7
    driver_plugin: vagrant
    driver_config:
      box: centos7

verifier:
  name: serverspec
  sudo: true
  sudo_path: true

transport:
  max_ssh_sessions: 6

suites:
  - name: rhel
    provisioner:
      name: ansible_playbook
      playbook: test/integration/rhel/test.yml
    verifier:
      bundler_path: /opt/rh/ruby200/root/usr/local/share/gems/gems/bundler-*/exe
      rspec_path: /opt/rh/ruby200/root/usr/local/share/gems/gems/rspec-core-*/exe
      default_pattern: true
